#!/usr/local/bin/zsh

export ZSH=$HOME/.oh-my-zsh
export ARCHFLAGS="-arch x86_64"
export HOMEBREW_CASK_OPTS="--appdir=/Applications"
export HOST_ENV="development"
export HISTCONTROL=ignoreboth:erasedupsG
export DOTFILES=$HOME/Dotfiles

export PATH=/usr/local/sbin:$HOME/.chromedriver:$PATH

# Needed for jekyll
# https://jekyllrb.com/docs/installation/macos/
export PATH=$HOME/.gem/ruby/2.5.0/bin:$PATH

# Needed for Vint
# https://github.com/Vimjas/vint
export PATH=$PATH:/Users/nate/Library/Python/3.10/bin/

plugins=(bundler osx rake ruby rails gem brew zsh-completions)
autoload -U compinit -u && compinit -u

# Create prompt
source $HOME/Dotfiles/zsh/zshrc_prompt

# Helper aliases/functions
source $DOTFILES/zsh/git.zsh
source $DOTFILES/zsh/tmux.zsh
source $DOTFILES/zsh/vagrant.zsh
source $DOTFILES/zsh/eslint.zsh
source $DOTFILES/zsh/fzf.zsh
source $DOTFILES/zsh/vim.zsh
source $DOTFILES/zsh/misc.zsh
source $DOTFILES/zsh/z.zsh
source $DOTFILES/zsh/docker.zsh
source $DOTFILES/zsh/heroku.zsh
source $DOTFILES/zsh/nvm.zsh
source $DOTFILES/zsh/notes.zsh

[ -f ~/.private_scripts.zsh ] && source ~/.private_scripts.zsh

setopt CORRECT
unsetopt inc_append_history
unsetopt share_history

# Colors when listing
export LD_BIND_NOW=1
export CLICOLOR=1
export LSCOLORS=GxBxhxDxfxhxhxhxhxcxcx

# Colors when using tab-completion in the command line
zstyle ':completion:*' list-colors "${(@s.:.)LS_COLORS}"
autoload -Uz compinit
compinit
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'

# Initialize FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Enable zsh syntax highlighting
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Run chruby scripts so that we use the correct ruby version
source /usr/local/share/chruby/chruby.sh
chruby ruby-2.7.2

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
