#!/usr/local/bin/zsh

# Set global ENV vars.
export ZSH=$HOME/.oh-my-zsh
export ARCHFLAGS="-arch x86_64"
export HOMEBREW_CASK_OPTS="--appdir=/Applications"
export HOST_ENV="development"
export HISTCONTROL=ignoreboth:erasedupsG
export DOTFILES=$HOME/Dotfiles
export EDITOR=nvim

[ -f ~/.before_init_private_scripts.sh ] && source ~/.before_init_private_scripts.sh

# Create prompt
source $HOME/Dotfiles/zsh/zshrc_prompt

# Zsh shell initializer
source $DOTFILES/zsh/zsh_shell_initializer.zsh

# Language initializers
source $DOTFILES/zsh/node.zsh
source $DOTFILES/zsh/ruby.zsh

# Helper aliases/functions
source $DOTFILES/shell_scripts/git.sh
source $DOTFILES/shell_scripts/tmux.sh
source $DOTFILES/shell_scripts/vim.sh
source $DOTFILES/shell_scripts/z.sh
source $DOTFILES/zsh/fzf.zsh
source $DOTFILES/zsh/docker.zsh
source $DOTFILES/zsh/notes.zsh
source $DOTFILES/zsh/misc.zsh

[ -f ~/.private_scripts.zsh ] && source ~/.private_scripts.zsh
