source ~/Dotfiles/shell_scripts/git.sh
source ~/Dotfiles/shell_scripts/tmux.sh
source ~/Dotfiles/shell_scripts/notes.sh
source ~/Dotfiles/shell_scripts/fzf.sh
source ~/Dotfiles/shell_scripts/z.sh
source ~/Dotfiles/shell_scripts/docker.sh
source ~/Dotfiles/shell_scripts/prompt.sh
source ~/Dotfiles/shell_scripts/vim.sh
source ~/Dotfiles/shell_scripts/misc.sh
source ~/Dotfiles/shell_scripts/ruby.sh
source ~/Dotfiles/shell_scripts/wsl_misc.sh
